/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package power60.services.app.ident.services

import com.mongodb.client.MongoClient
import com.mongodb.client.MongoClients
import com.mongodb.client.MongoCollection
import com.mongodb.client.MongoDatabase
import com.mongodb.client.result.InsertOneResult
import org.bson.Document


class IdentMongoClient {

    companion object {

        private val mongoClient: MongoClient = MongoClients.create()
        private val auth: MongoDatabase = mongoClient.getDatabase("auth")
        private val accountsCollection: MongoCollection<Document> = auth.getCollection("accounts")


        fun createAccount(account: Document): InsertOneResult {
            return accountsCollection.insertOne(account)
        }

        fun searchAccounts() {

        }

        fun updateAccount() {

        }
    }
}
